// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lfocrnmwwliaiguvskuf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxmb2Nybm13d2xpYWlndXZza3VmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI4Mjg3NjYsImV4cCI6MjA2ODQwNDc2Nn0.nxNRutbikZBOj89rIhwkyLMvA1V_25MGgeTpnPDAFJo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});